# -*- coding: utf-8 -*-
"""data preprocessing_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuHzrN-9arBzoNh996hbqYJmTKU9B4a0
"""

import pandas as pd

df = pd.read_csv('/content/demo1.csv')
df.shape

print(df)

#### remove column contains NAN values
df1 = df.dropna(axis=1)
print(df1)

### remove rows within NAN values
df2 = df.dropna(axis=0)
print(df2)

### remove rows where columns are NAN
df3 = df.dropna(axis=0, how='all')
print(df3)

### remove rows where any of column is NAN
df4 = df.dropna(axis=0, how='any')
print(df4)

### delete rows when not have threshold non-NAN values
df5 = df.dropna(axis=0, thresh=2)
print(df5)

### delete rows if NAN appears in specific column
df6 = df.dropna(axis=0, subset=['Height'])
print(df6)

df7 =df.copy()
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')
df7[['Height']] = si.fit_transform(df7[['Height']])
df7[['Weight']] = si.fit_transform(df7[['Weight']])
print(df7)

df7=pd.DataFrame(df7)
df7.columns=['Ethinicity','Height','Weight','Survive']
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df7['Ethinicity']=le.fit_transform(df7['Ethinicity'])
df7['Survive']=le.fit_transform(df7['Survive'])
print(df7)

ohe1 = pd.get_dummies(df['Ethinicity'])
print(ohe1)

from sklearn.preprocessing import OneHotEncoder
ohe2 = OneHotEncoder()
df8 = ohe2.fit_transform(df[['Ethinicity']])
print(df8)

si=SimpleImputer(strategy='most_frequent')
df10 = si.fit_transform(df)
print(df10)

df10=pd.dataFrame(df10)
print(df10)